
import { GoogleAnalytics } from '@next/third-parties/google'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <GoogleAnalytics gaId="G-MHDY389QFB" />
      <body>{children}</body>
    </html>
  )
}
